Fix failure about grunt serve task
  % grunt serve
  Loading "connect_proxy.js" tasks...ERROR
  >> TypeError: The super constructor to `inherits` must not be null or undefined.

  Running "serve" task
  Warning: Task "configureProxies:server" not found. Use --force to continue.

  Aborted due to warnings.

See related issue about "Grunt serve doesn't work anymore"
  https://github.com/gruntjs/grunt/issues/1315